valued:
  - "ident"
  - "lit_int"
  - "lit_float"
  - "lit_char"
  - "lit_str"
  - "lit_str_raw"
  - "err"
  
words:
  - "word_let"
  - "word_if"
  - "word_then"
  - "word_else"
  - "word_elif"
  - "word_case"
  - "word_of"
  - "word_end"
  - "word_while"
  - "word_for"
  - "word_in"
  - "word_do"
  - "word_done"
  - "word_break"
  - "word_continue"
  - "word_match"
  - "word_when"
  - "word_type"
  - "word_record"
  - "word_union"
  - "word_fn"
  - "word_const"
  - "word_import"
  - "word_use"
  - "word_and"
  - "word_or"
  - "word_xor"
  - "word_not"
  - "lit_true"
  - "lit_false"

eofToken:
  - "eof"

shortSymbols:
  - ["paren_l",   "("]
  - ["paren_r",   ")"]
  - ["bracket_l", "["]
  - ["bracket_r", "]"]
  - ["brace_l",   "{"]
  - ["brace_r",   "}"]
  - ["dot",       "."]
  - ["comma",     ","]
  - ["semicolon", ";"]
  - ["colon",     ":"]
  - ["equals",    "="]
  - ["vert_line", "|"]
  - ["bang",      "!"]
  - ["minus",     "-"]
  - ["plus",      "+"]
  - ["star",      "*"]
  - ["slash",     "/"]
  - ["percent",   "%"]
  - ["less",      "<"]
  - ["greater",   ">"]

longSymbols:
  - ["comp_eq",      "=="]
  - ["comp_ne",      "!="]
  - ["comp_le",      "<="]
  - ["comp_ge",      ">="]
  - ["arrow",        "->"]
  - ["return_arrow", "=>"]
  - ["fwd_compose",  ">>"]
  - ["range",        ".."]
  - ["range_incl",   ".:"]
  - ["module",       "::"]
  - ["concat",       "++"]
